[package]
name = "convergence"
version = "0.1.0"
authors = ["Ruan Pearce-Authers <ruan@reservoirdb.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.0", features = [ "net", "rt-multi-thread", "macros", "io-util", "io-std" ] }
tokio-util = { version = "0.6", features = [ "codec" ] }
thiserror = "1.0"
bytes = "1.0"
futures = "0.3"
sqlparser = "0.9"
async-trait = "0.1"

[dev-dependencies]
tokio-postgres = "0.7"
