[package]
name = "convergence-arrow"
version = "0.1.0"
authors = ["Ruan Pearce-Authers <ruan@reservoirdb.com>"]
edition = "2018"
description = "Utils for bridging Apache Arrow and PostgreSQL's wire protocol"
license = "MIT"
repository = "https://github.com/reservoirdb/convergence"

[dependencies]
tokio = { version = "1.0" }
sqlparser = "0.9"
async-trait = "0.1"
arrow = { git = "https://github.com/apache/arrow" }
convergence = { path = "../convergence", version = "0.1" }

[dev-dependencies]
tokio-postgres = "0.7"
datafusion = { git = "https://github.com/apache/arrow" }
