[package]
name = "convergence-arrow"
version = "0.1.0"
authors = ["Ruan Pearce-Authers <ruan@reservoirdb.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.0" }
sqlparser = "0.9"
async-trait = "0.1"
arrow = "3.0"
convergence = { path = "../convergence", version = "0.1" }

[dev-dependencies]
tokio-postgres = "0.7"
